/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardBanner: typeof import('./src/components/CardBanner.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PaginaInicial: typeof import('./src/components/PaginaInicial.vue')['default']
  }
}
